#!/bin/bash
# Artwork Merge Script - Complete Usage Guide
# Updated: January 2, 2026

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║        Artwork Merge Script - Complete Usage Guide                ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ SCRIPT IS READY TO USE!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 PREREQUISITES (Already Done)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✓ Script fixed to find .env files in project root"
echo "  ✓ Script fixed to find Images directory correctly"
echo "  ✓ Category formatting implemented (no spaces, title case)"
echo "  ✓ Featured artworks configured (Maypole Unicorn, Christmas Animals)"
echo "  ✓ Date conversion working (year → DATE format)"
echo "  ✓ All 68 artworks validated with 0 errors"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 HOW TO RUN (from scripts/ directory OR project root)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  DRY RUN (recommended first - shows what will happen):"
echo "    cd scripts"
echo "    python3 merge_artworks.py --env dev --dry-run"
echo ""
echo "2️⃣  DRY RUN with detailed output:"
echo "    python3 merge_artworks.py --env dev --dry-run --verbose"
echo ""
echo "3️⃣  ACTUAL IMPORT (development database):"
echo "    python3 merge_artworks.py --env dev"
echo ""
echo "4️⃣  ACTUAL IMPORT (production database):"
echo "    python3 merge_artworks.py --env prod"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ WHAT THE SCRIPT DOES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 Reads Data:"
echo "   • Scans all 68 artwork directories in backend/src/main/resources/Images/"
echo "   • Parses .txt files for metadata"
echo "   • Finds LARGEST .jpg for large_image_url"
echo ""
echo "🎨 Formats Categories:"
echo "   • Input:  'acrylic, painting, paint pouring, insects, abstract'"
echo "   • Output: 'Acrylic,Painting,Paint Pouring,Insects,Abstract'"
echo "   • No spaces after commas, title case for each word"
echo "   • Original .txt files unchanged"
echo ""
echo "💾 Inserts to Database:"
echo "   • Uses PostgreSQL UPSERT (safe to run multiple times)"
echo "   • Sets is_featured=TRUE only for Maypole Unicorn & Christmas Animals"
echo "   • Converts years to proper DATE format (e.g., '2024' → '2024-01-01')"
echo "   • Sets created_at and updated_at timestamps"
echo "   • Parses prices and determines for_sale status"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 VERIFY RESULTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check total count:"
echo "  docker exec lindsey-website-postgres-1 psql -U toadMan -d lindseydb \\"
echo "    -c 'SELECT COUNT(*) FROM artworks;'"
echo ""
echo "View featured artworks:"
echo "  docker exec lindsey-website-postgres-1 psql -U toadMan -d lindseydb \\"
echo "    -c \"SELECT title, is_featured FROM artworks WHERE is_featured = TRUE;\""
echo ""
echo "Check category formatting:"
echo "  docker exec lindsey-website-postgres-1 psql -U toadMan -d lindseydb \\"
echo "    -c \"SELECT title, categories FROM artworks LIMIT 5;\""
echo ""
echo "View a specific artwork:"
echo "  docker exec lindsey-website-postgres-1 psql -U toadMan -d lindseydb \\"
echo "    -c \"SELECT * FROM artworks WHERE title = 'The Christmas Animals';\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 FRONTEND INTEGRATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "TypeScript Example:"
echo "  const categories = artwork.categories.split(',');"
echo "  // ['Acrylic', 'Painting', 'Paint Pouring', 'Nature']"
echo ""
echo "Filter by category:"
echo "  const filtered = artworks.filter(art => "
echo "    art.categories.split(',').includes('Acrylic')"
echo "  );"
echo ""
echo "Get all unique categories:"
echo "  const allCategories = new Set("
echo "    artworks.flatMap(art => art.categories.split(','))"
echo "  );"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🛠️  TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Error: 'Environment file not found'"
echo "  → Make sure .env.dev or .env.prod exists in project root"
echo "  → Script now looks in parent directory automatically"
echo ""
echo "Error: 'connection refused'"
echo "  → Start postgres: docker compose up -d postgres"
echo "  → Wait a few seconds for postgres to start"
echo ""
echo "Error: 'No valid artwork directories found'"
echo "  → Check that Images directory exists"
echo "  → Path should be: backend/src/main/resources/Images/"
echo ""
echo "Error: 'ModuleNotFoundError: psycopg2'"
echo "  → Install: pip3 install psycopg2-binary python-dotenv"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Documentation:"
echo "   • scripts/MERGE_SCRIPT_SUMMARY.md"
echo "   • scripts/CATEGORY_FORMATTING_GUIDE.md"
echo ""
echo "🎉 YOU'RE READY TO GO!"
echo ""

